---
output: html_document
title: Rec DST
---





This shiny application was developed to make the Recreation Demand Model (RDM) for Summer Flounder, Black Sea Bass, and Scup directly accessible to Fisheries Managers. If you have questions, please reach out to Kimberly Bastille (kimberly.bastille@noaa.gov) and Andrew (Lou) Carr-Harris (andrew.carr-harris@noaa.gov).

Details and meeting notes from the Recreational Demand Model Decision Support Tool Working Group can be found at [NOAA Fisheries](https://www.fisheries.noaa.gov/event/recreational-demand-model-decision-support-tool-working-group-summer-flounder-black-sea-bass). 


## Topics to fill out 

### How to use the app flow chart?

### Summary description for each output table

#### Regulations

This is a summary table of the regulations chosen in the `Regulation Selection` tab in the application. This shows the state, mode, season, bag limit and length parameters that are used to calculate the following outputs. 

#### Keep/Release

This table uses the regulation inputs from above to calculate the estimated harvest (keep) and discard (release) both by number of fish and weight in pounds by mode. StatusQuo is the estimate if the regulation parameters did not change from the previous year. This is compared to the Alternative which is the estimate based on the selected regulation parameters.   

#### Angler_Welfare

Angler Welfare - Definition

#### Discard Mortality

Discard mortality uses the same format as the Keep and Release table. It takes the Releases and multiplies it by the discard mortality rate. This gives an estimate of the number of fish and weight of discard deaths. The discard mortality rates are 10% for summer flounder and 15% for black sea bass and scup. This assumes that 10 or 15 percent of the fish release will die. 

### Data inputs summary

- Angler Discrete Choice Experiment
- MRIP
- Volunteer Angler Survey
- length-weight equations for each spp

### link to description of the model