apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile-dataraw-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: true
    volumeHandle: dataraw  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: RESOURCE_GROUP  # optional, only set this when storage account is not in the same resource group as node
      shareName: data-raw
      storageAccount: STORAGE_ACCOUNT_NAME
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0755
    - file_mode=0755
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl